networks:
  radireporter:

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped

  app:
    depends_on:
      - postgres
    build:
      context: .
    environment:
      CONFIG_PATH: "/etc/config.yaml"
    volumes:
      - ./config.test.yaml:/etc/config.yaml:z
    networks:
      - radireporter
    restart: always
