name: build-test
on:
  push:
    branches:
      - "main"
      - "dev"
      - "release-**"
  pull_request:
    branches:
      - "main"
      - "dev"

permissions:
  contents: read

env:
  GOLANG_VERSION: '1.16' # Set the desired Go version here

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # pin@v4.2.2
      - name: Setup Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # pin@5.5.0
        with:
          go-version: '${{ env.GOLANG_VERSION }}'
          check-latest: true
      - name: Run unit tests
        run: make test-coverage
      - name: Test build
        run: make build